//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping
    {
        public int MappingId { get; set; }
        public int StudentId { get; set; }
        public int TeacherId { get; set; }
        public string Subject { get; set; }
        public string Room { get; set; }
        public System.DateTime RecCreatedDate { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
